{% set name = "django-safedelete" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-safedelete-{{ version }}.tar.gz
  sha256: 27ce5f92d7f4c6adab67c085420aa8c2a8e6751a7fb4a1c0afa70547ddeb2d7d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - django
    - python >={{ python_min }}

test:
  commands:
    - pip check
    # django settings configuration must be setup before safedelete can be imported
    - python -c "from django.conf import settings;settings.configure();import safedelete"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/makinacorpus/django-safedelete
  summary: Mask your objects instead of deleting them from your database.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
